# Generated by Django 6.1.1 on 2026-09-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('plataforma', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('jogando', 'Jogando'), ('concluido', 'Concluído'), ('backlog', 'Na Fila / Backlog'), ('abandonado', 'Abandonei')], default='backlog', max_length=20)),
                ('nota', models.IntegerField(default=0)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
