# Generated by Django 6.1.1 on 2026-09-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Imagem'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='nota',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='plataforma',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='status',
            field=models.CharField(default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
