# Generated by Django 6.1.1 on 2026-09-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_jogo_imagem_url_alter_jogo_descricao_alter_jogo_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='status',
            field=models.CharField(choices=[('A Jogar', 'A Jogar'), ('Jogando', 'Jogando'), ('Concluído', 'Concluído'), ('Abandonado', 'Abandonado')], default='A Jogar', max_length=20),
        ),
    ]
