# Generated by Django 6.1.1 on 2026-10-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0003_alter_jogo_descricao_alter_jogo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Preço (R$)'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='plataforma',
            field=models.CharField(choices=[('PC', 'Computador (PC)'), ('PlayStation', 'PlayStation'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo'), ('Mobile', 'Telemóvel / Tablet'), ('Outro', 'Outra Plataforma')], default='PC', max_length=20),
        ),
    ]
