# Generated by Django 6.1.1 on 2026-10-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0004_jogo_preco_alter_jogo_plataforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('plataforma', models.CharField(choices=[('PC', 'Computador (PC)'), ('PlayStation', 'PlayStation'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo'), ('Mobile', 'Telemóvel / Tablet'), ('Outro', 'Outra Plataforma')], default='PC', max_length=20)),
                ('imagem_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Imagem')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Preço (R$)')),
                ('eh_gratis', models.BooleanField(default=False, verbose_name='É Gratuito?')),
                ('link_compra_jogar', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link para Jogar/Comprar')),
                ('descricao', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Jogo da Loja',
                'verbose_name_plural': 'Jogos da Loja',
            },
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='preco',
        ),
    ]
